version: '3.7'
services:

  db:
    image: mysql:5.7
    restart: always
    ports: 
      - "3307:3306"
    # local to the project directory only for demo purposes
    volumes:
      - ./.db:/var/lib/mysql:rw,delegated
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - rails_service
      - go_service

  rails_service:
    build:
      context: ./rails_service
    command:  bash -c "rm -f /app/tmp/pids/server.pid && rake db:migrate && bundle exec whenever --update-crontab && cron -f && bundle exec rails s -p 3000 -b '0.0.0.0' & rake sneakers:run"
    env_file:
      - .env
    volumes: 
      - ./rails_service:/app
    ports: 
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    env_file:
      - .env

  redis:
    restart: always
    image: redis:alpine
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  go_service:
    build:
      context: ./go_service
    volumes: 
      - ./go_service:/app
    ports: 
      - "8000:8000"
    env_file:
      - .env
